runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /(.+)/
  static_files: www/\1/index.html
  upload: www/(.+)/index.html

- url: /
  static_files: www/index.html
  upload: www/index.html

- url: /([^\.]+)([^/])
  static_files: www/\1\2/index.html
  upload: www/(.+)

- url: /(.+)
  static_files: www/\1
  upload: www/(.+)